defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}
seed: -1

model: resnet
unlearning_method: icus
forgetting_set_strategy: random_classes
forgetting_set: random
forgetting_set_size: 2

dataset: 
  name: cifar10
  path: ./data
  classes: 10
  resize: 224

device: "cuda"
SSDdampening: 0.5
SSDselectwt: 0.1

train:
  batch_size: 32
  max_epochs: 140
  lr: 1e-3
  save_path: checkpoints/
  num_workers: 1
  patience: 10

train_iters: 999
max_epochs: 10
temp: 1

log:
  path: ./logs
  wandb: True

wandb:
  project: icus
  entity: fedefrati-universit-di-pisa



