defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}
seed: -1

model: resnet
unlearning_method: icus
forgetting_set_strategy: random_class
forgetting_set: random
forgetting_set_size: 2

dataset: 
  name: cifar10
  path: ./data
  classes: 10
  resize: 224

device: "cuda"

train:
  batch_size: 32
  max_epochs: 100
  lr: 1e-3
  save_path: checkpoints/
  num_workers: 1
  patience: 10

unlearn:
  lr: 1e-4
  max_epochs: 1000
  temp: 1
  scrub_steps: 7
  nlayers: [1,2]
  cos_sim_factor: 0.0
  SSDdampening: 0.5
  SSDselectwt: 0.1

train_iters: 999

log:
  path: ./logs
  wandb: True

wandb:
  project: icus
  entity: fedefrati-universit-di-pisa

