defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}
seed: 42

model: resnet
unlearning_method: icus
forgetting_set: random
forgetting_set_size: 4

dataset: 
  name: cifar10
  path: ./data
  classes: 10
  resize: 224

device: "cuda"

train:
  batch_size: 64
  max_epochs: 10
  lr: 1e-3
  save_path: ./models
  num_workers: 1
  patience: 10

train_iters: 2000
max_epochs: 5

log:
  path: ./logs
  wandb: True

wandb:
  project: icus
  entity: fedefrati-universit-di-pisa



