defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}
seed: -1

model: resnet
unlearning_method: icus
forgetting_set_strategy: random_values
forgetting_set: random
forgetting_set_size: 3

dataset: 
  name: cifar10
  path: ./data
  classes: 10
  resize: 224

device: "cuda"

train:
  batch_size: 64
  max_epochs: 20
  lr: 1e-3
  save_path: ./models
  num_workers: 1
  patience: 10

train_iters: 250
max_epochs: 10

log:
  path: ./logs
  wandb: True

wandb:
  project: icus
  entity: fedefrati-universit-di-pisa



