defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}
seed: -1

model: resnet
weights_name: ResNet18_Weights.IMAGENET1K_V1
unlearning_method: icus
forgetting_set_strategy: random_class
forgetting_set: [4,22,49,51,63,68,72,79,88,93]
forgetting_set_size: 10
golden_model: False
original_model: False

dataset: 
  name: cifar10
  path: ./data
  classes: 10
  resize: 224

device: "cuda"

train:
  batch_size: 32
  max_epochs: 120
  lr: 5e-4
  save_path: checkpoints/
  num_workers: 1
  patience: 10

unlearn:
  lr: 1e-4
  max_epochs: 10000
  temp: 1
  scrub_steps: 7
  nlayers: [1,2]
  cos_sim_factor: 0.0
  SSDdampening: 0.5
  SSDselectwt: 0.1
  update_json: False
  reconstruct_from_d: False
  already_forgotten_classes: []
  aggregation_method: mean

train_iters: 999

log:
  path: ./logs
  wandb: True

wandb:
  project: icus
  entity: fedefrati-universit-di-pisa

