defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}
seed: -1

model: resnet
weights_name: ResNet18_Weights.IMAGENET1K_V1
unlearning_method: icus
forgetting_set_strategy: random_class
forgetting_set: [64,2,44,88,81,53,24,28,67,82,80,55,66,34,29,35,5,86,93,73]
forgetting_set_size: 20
golden_model: False
original_model: False

dataset: 
  name: cifar100
  path: ./data
  classes: 100
  resize: 224

device: "cuda"

train:
  batch_size: 32
  max_epochs: 120
  lr: 5e-4
  save_path: checkpoints/
  num_workers: 1
  patience: 10

unlearn:
  lr: 1e-4
  max_epochs: 1000
  temp: 1
  scrub_steps: 7
  nlayers: [1,2]
  cos_sim_factor: 0.0
  SSDdampening: 0.5
  SSDselectwt: 0.1
  update_json: False

train_iters: 999

log:
  path: ./logs
  wandb: True

wandb:
  project: icus
  entity: fedefrati-universit-di-pisa

