defaults:
  - _self_
  - dataset_info
  - target_layers

currentDir: ${hydra:runtime.cwd}
seed: 42

model: resnet
unlearning_method: scrub
forgetting_set: random
forgetting_set_size: 4

dataset: 
  name: cifar10
  path: ./data
  resize: 224

device: "cuda"

train:
  batch_size: 16
  max_epochs: 20
  lr: 1e-6
  save_path: ./models
  num_workers: 1
  patience: 10

log:
  path: ./logs
  wandb: True

wandb:
  project: icus
  entity: marcoparola



